# Generated by Django 5.1.6 on 2025-02-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='InspectionPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Namangan', 'Namangan'), ('Andijan', 'Andijan'), ('Fergana', 'Fergana'), ('Navoi', 'Navoi'), ('Surkhandarya', 'Surkhandarya'), ('Kashkadarya', 'Kashkadarya'), ('Sirdarya', 'Sirdarya'), ('Khorezm', 'Khorezm'), ('Jizzakh', 'Jizzakh'), ('Karakalpakstan', 'Karakalpakstan')], max_length=255, verbose_name='Region')),
                ('district', models.CharField(max_length=255, verbose_name='District')),
            ],
            options={
                'verbose_name': 'Inspection Place',
                'verbose_name_plural': 'Inspection Places',
            },
        ),
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comparisons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='main.announcement')),
            ],
        ),
    ]
