# Generated by Django 5.1.6 on 2025-02-18 08:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_announcement_slug_announcement_slug_from_lang'),
        ('projects', '0003_searchmodel_delete_searches'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comparisons',
            options={'verbose_name': 'Taqqoslash', 'verbose_name_plural': 'Taqqoslashlar'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'Sevimli', 'verbose_name_plural': 'Sevimlilar'},
        ),
        migrations.AlterModelOptions(
            name='inspectionplace',
            options={'verbose_name': 'Texnik ko‘rik joyi', 'verbose_name_plural': 'Texnik ko‘rik joylari'},
        ),
        migrations.AlterField(
            model_name='comparisons',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparisons', to='main.announcement', verbose_name='Taqqoslanayotgan avtomobil'),
        ),
        migrations.AlterField(
            model_name='comparisons',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparison', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites_cars', to='main.announcement', verbose_name='Sevimli avtomobil'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqt'),
        ),
        migrations.AlterField(
            model_name='favorites',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='inspectionplace',
            name='district',
            field=models.CharField(max_length=255, verbose_name='Tuman'),
        ),
        migrations.AlterField(
            model_name='inspectionplace',
            name='region',
            field=models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Namangan', 'Namangan'), ('Andijan', 'Andijan'), ('Fergana', 'Fergana'), ('Navoi', 'Navoi'), ('Surkhandarya', 'Surkhandarya'), ('Kashkadarya', 'Kashkadarya'), ('Sirdarya', 'Sirdarya'), ('Khorezm', 'Khorezm'), ('Jizzakh', 'Jizzakh'), ('Karakalpakstan', 'Karakalpakstan')], max_length=255, verbose_name='Viloyat'),
        ),
        migrations.DeleteModel(
            name='SearchModel',
        ),
    ]
