# Generated by Django 5.1.6 on 2025-02-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Kiritilgan sana')),
                ('updated_at', models.DateField(auto_now=True, verbose_name="o'zgartrilgan sana")),
                ('entities_id', models.BigIntegerField()),
                ('video_url', models.URLField()),
                ('caption', models.TextField()),
                ('likes', models.BigIntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announ_reel', to='main.announcement')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
