# Generated by Django 5.1.6 on 2025-02-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reels',
            name='caption_ru',
            field=models.TextField(null=True, verbose_name='Foydalanuvchi commenti'),
        ),
        migrations.AddField(
            model_name='reels',
            name='caption_uz',
            field=models.TextField(null=True, verbose_name='Foydalanuvchi commenti'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='caption',
            field=models.TextField(verbose_name='Foydalanuvchi commenti'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='entities_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reels',
            name='likes',
            field=models.BigIntegerField(default=0, verbose_name='Likes'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='video_url',
            field=models.URLField(verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='reels',
            name='view_count',
            field=models.BigIntegerField(default=0, verbose_name="Ko'rishlar soni"),
        ),
    ]
