# Generated by Django 5.1.6 on 2025-02-16 05:44

import apps.common.models.fields
import apps.common.utils
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceDealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Car_Dealer', 'Car Dealer')], max_length=50, verbose_name='Dealer Type')),
                ('dealer_sub_type', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50, verbose_name='Dealer Sub Type')),
                ('name', models.CharField(max_length=255, verbose_name='Dealer Name')),
                ('address', models.TextField(verbose_name='Address')),
                ('phone_number', apps.common.models.fields.PhoneField(max_length=15, validators=[django.core.validators.RegexValidator(message='15-ta raqamga ruxsat berilgan. Standard raqam talab qilinadi', regex='^\\+?1?\\d{9,15}$')], verbose_name='Phone Number')),
                ('working_hours', models.CharField(max_length=255, verbose_name='Working Hours')),
                ('number_of_cars', models.PositiveIntegerField(default=0, verbose_name='Number of Cars')),
                ('logo', models.ImageField(blank=True, null=True, upload_to=apps.common.utils.generate_upload_path, verbose_name='Dealer Logo')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Service Dealer',
                'verbose_name_plural': 'Service Dealers',
                'ordering': ('id',),
            },
        ),
    ]
