# Generated by Django 5.1.6 on 2025-02-18 10:12

import apps.common.models.fields
import apps.common.utils
import django.core.validators
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='servicedealer',
            options={'ordering': ('id',), 'verbose_name': 'Xizmat dileri', 'verbose_name_plural': 'Xizmat dilerlari'},
        ),
        migrations.AddField(
            model_name='servicedealer',
            name='location_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='joylashinuvi'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='address',
            field=models.TextField(verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='dealer_sub_type',
            field=models.CharField(choices=[('New', 'Yangi'), ('Used', 'Ishlatilgan')], max_length=50, verbose_name="Diler qo'shimcha turi"),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='latitude',
            field=models.FloatField(verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='logo',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=apps.common.utils.generate_upload_path, verbose_name='Diler logotipi'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='longitude',
            field=models.FloatField(verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Diler nomi'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='number_of_cars',
            field=models.PositiveIntegerField(default=0, verbose_name='Ish soatlari'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='phone_number',
            field=apps.common.models.fields.PhoneField(max_length=15, validators=[django.core.validators.RegexValidator(message='15-ta raqamga ruxsat berilgan. Standard raqam talab qilinadi', regex='^\\+?1?\\d{9,15}$')], verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='type',
            field=models.CharField(choices=[('Car_Dealer', 'Avtomobil dileri')], max_length=50, verbose_name='Diler turi'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='working_hours',
            field=models.CharField(max_length=255, verbose_name='Ish soatlari'),
        ),
    ]
