# Generated by Django 5.1.6 on 2025-02-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_alter_servicedealer_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicedealer',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Kenglik'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Uzunlik'),
        ),
        migrations.AlterField(
            model_name='servicedealer',
            name='number_of_cars',
            field=models.PositiveIntegerField(default=0, verbose_name='Moshina raqami'),
        ),
    ]
