# Generated by Django 5.1.6 on 2025-02-16 05:44

import apps.common.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', apps.common.models.fields.ActiveField(default=False, verbose_name='active')),
                ('key', models.CharField(max_length=500)),
                ('key_uz', models.CharField(max_length=500, null=True)),
                ('key_ru', models.CharField(max_length=500, null=True)),
                ('value', models.TextField()),
                ('value_uz', models.TextField(null=True)),
                ('value_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Site Setting',
                'verbose_name_plural': 'Site Settings',
                'ordering': ('key',),
            },
        ),
    ]
