# Generated by Django 5.1.6 on 2025-02-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Foydalanuvchilar', 'verbose_name_plural': 'Foydalanuvchilar'},
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone_number_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture_uz',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_ru',
        ),
        migrations.RemoveField(
            model_name='user',
            name='region_uz',
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name',
            field=models.CharField(max_length=255, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='F.I.Sh'),
        ),
        migrations.AlterField(
            model_name='user',
            name='region',
            field=models.CharField(choices=[('Tashkent', 'Tashkent'), ('Samarkand', 'Samarkand'), ('Bukhara', 'Bukhara'), ('Namangan', 'Namangan'), ('Andijan', 'Andijan'), ('Fergana', 'Fergana'), ('Navoi', 'Navoi'), ('Surkhandarya', 'Surkhandarya'), ('Kashkadarya', 'Kashkadarya'), ('Sirdarya', 'Sirdarya'), ('Khorezm', 'Khorezm'), ('Jizzakh', 'Jizzakh'), ('Karakalpakstan', 'Karakalpakstan')], max_length=255, verbose_name='Yashash manzili'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_count_data',
            field=models.BigIntegerField(default=0, verbose_name='Foydalanuvchining malumotlar son'),
        ),
    ]
