# Generated by Django 5.1.6 on 2025-02-16 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='inspection_place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspected_announcements', to='projects.inspectionplace'),
        ),
    ]
