# Generated by Django 5.1.6 on 2025-02-16 05:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bodystatus',
            name='body_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodypart', to='main.bodyparts'),
        ),
        migrations.AddField(
            model_name='bodystatus',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_status', to='main.announcement'),
        ),
        migrations.AddField(
            model_name='bodystatus',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='main.bodyconditions'),
        ),
        migrations.AddField(
            model_name='caroptionsmapping',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caroptionmapping', to='main.announcement'),
        ),
        migrations.AddField(
            model_name='caroptionsmapping',
            name='car_options_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_option', to='main.caroption'),
        ),
        migrations.AddField(
            model_name='images',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.announcement'),
        ),
        migrations.AddField(
            model_name='prices',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.announcement'),
        ),
    ]
