# Generated by Django 5.1.6 on 2025-02-16 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Elon', 'verbose_name_plural': '1. Elonlar'},
        ),
        migrations.AlterModelOptions(
            name='bodyconditions',
            options={'verbose_name': 'Holati', 'verbose_name_plural': '6. Holatlari'},
        ),
        migrations.AlterModelOptions(
            name='bodyparts',
            options={'verbose_name': 'Moshina tanasi', 'verbose_name_plural': '5. Moshina tanasi'},
        ),
        migrations.AlterModelOptions(
            name='bodystatus',
            options={'verbose_name': 'Tana qismlarining xolati', 'verbose_name_plural': '7. Tana qismlarining xolati'},
        ),
        migrations.AlterModelOptions(
            name='caroption',
            options={'ordering': ('name',), 'verbose_name': 'Optsiya nomi', 'verbose_name_plural': '3. Optsiya nomlari'},
        ),
        migrations.AlterModelOptions(
            name='caroptionsmapping',
            options={'verbose_name': 'Mashina optsiyalar xaritasi', 'verbose_name_plural': '4. Moshina optsiyalar xaritasi'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Rasm', 'verbose_name_plural': '8. Rasmlar'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'ordering': ('price',), 'verbose_name': 'Narx', 'verbose_name_plural': '2. Narxlar'},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='mileage',
            new_name='milage',
        ),
        migrations.AddField(
            model_name='announcement',
            name='body_type_ru',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe')], max_length=100, null=True, verbose_name='Body Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='body_type_uz',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe')], max_length=100, null=True, verbose_name='Body Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='brand_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Car Brand'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='brand_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Car Brand'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='color_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='color_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='fuel_type_ru',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100, null=True, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='fuel_type_uz',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100, null=True, verbose_name='Fuel Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='gas_type_ru',
            field=models.CharField(blank=True, choices=[('Methane', 'Methane'), ('Propane', 'Propane'), ('Butane', 'Butane')], max_length=100, null=True, verbose_name='Gas Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='gas_type_uz',
            field=models.CharField(blank=True, choices=[('Methane', 'Methane'), ('Propane', 'Propane'), ('Butane', 'Butane')], max_length=100, null=True, verbose_name='Gas Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='gearbox_type_ru',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10, null=True, verbose_name='Transmission'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='gearbox_type_uz',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10, null=True, verbose_name='Transmission'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='generation_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Generation'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='generation_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Generation'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='model_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Car Model'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='model_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Car Model'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='ownership_type_ru',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Company', 'Company'), ('Rental', 'Rental')], max_length=255, null=True, verbose_name='Ownership Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='ownership_type_uz',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Company', 'Company'), ('Rental', 'Rental')], max_length=255, null=True, verbose_name='Ownership Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='passport_type_ru',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Import', 'Import')], max_length=100, null=True, verbose_name='Passport Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='passport_type_uz',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Import', 'Import')], max_length=100, null=True, verbose_name='Passport Type'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status_ru',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Unsold', 'Unsold')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='status_uz',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Unsold', 'Unsold')], max_length=100, null=True, verbose_name='Status'),
        ),
        migrations.AddField(
            model_name='caroption',
            name='name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Moshina opsiyalari'),
        ),
        migrations.AddField(
            model_name='caroption',
            name='name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Moshina opsiyalari'),
        ),
        migrations.AddField(
            model_name='prices',
            name='currency_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Valyuta turi'),
        ),
        migrations.AddField(
            model_name='prices',
            name='currency_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Valyuta turi'),
        ),
    ]
