# Generated by Django 5.1.6 on 2025-02-16 13:43

import apps.common.utils
import sorl.thumbnail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='body_type_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='body_type_uz',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='fuel_type_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='fuel_type_uz',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='gas_type_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='gas_type_uz',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='gearbox_type_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='gearbox_type_uz',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='ownership_type_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='ownership_type_uz',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='passport_type_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='passport_type_uz',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='status_ru',
        ),
        migrations.RemoveField(
            model_name='announcement',
            name='status_uz',
        ),
        migrations.AlterField(
            model_name='announcement',
            name='body_type',
            field=models.CharField(blank=True, choices=[('Sedan', 'Sedan'), ('Coupe', 'Coupe')], max_length=100, null=True, verbose_name='Kuzov turi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Mashina modeli'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='brand_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Mashina modeli'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='brand_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Mashina modeli'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='color_ru',
            field=models.CharField(max_length=50, null=True, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='color_uz',
            field=models.CharField(max_length=50, null=True, verbose_name='Rang'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description',
            field=models.TextField(verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_ru',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='description_uz',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='engine_capacity',
            field=models.PositiveIntegerField(help_text='Enter in cc or liters', verbose_name='Dvigatel hajmi (kub sm yoki litr)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='favorite_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Saqlanganlar soni'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='fuel_type',
            field=models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=100, verbose_name='Yoqilg‘i turi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='gas_type',
            field=models.CharField(blank=True, choices=[('Methane', 'Methane'), ('Propane', 'Propane'), ('Butane', 'Butane')], max_length=100, null=True, verbose_name='Gaz turi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='gearbox_type',
            field=models.CharField(choices=[('Automatic', 'Automatic'), ('Manual', 'Manual')], max_length=10, verbose_name='Uzatmalar qutisi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='generation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avlod'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='generation_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avlod'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='generation_uz',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Avlod'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='is_daily_offer',
            field=models.BooleanField(default=False, verbose_name='Kunlik taklif'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='milage',
            field=models.BigIntegerField(default=0, verbose_name='Yurgan masofa (km)'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='ownership_type',
            field=models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Company', 'Company'), ('Rental', 'Rental')], max_length=255, null=True, verbose_name='Egalik turi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='passport_type',
            field=models.CharField(blank=True, choices=[('Local', 'Local'), ('Import', 'Import')], max_length=100, null=True, verbose_name='Pasport turi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='power',
            field=models.PositiveIntegerField(verbose_name='Ot kuchi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='Mashina narxi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='purchase_date',
            field=models.DateField(blank=True, null=True, verbose_name='Xarid qilingan sana'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='status',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Unsold', 'Unsold')], max_length=100, verbose_name='Holat'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='year',
            field=models.PositiveIntegerField(verbose_name='Ishlab chiqarilgan yil'),
        ),
        migrations.AlterField(
            model_name='bodyconditions',
            name='condition_name',
            field=models.CharField(max_length=255, verbose_name='Moshina xolati'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image_url',
            field=sorl.thumbnail.fields.ImageField(upload_to=apps.common.utils.generate_upload_path, verbose_name='rasmlar'),
        ),
        migrations.AlterField(
            model_name='images',
            name='is_main',
            field=models.BooleanField(verbose_name='Asosi'),
        ),
    ]
