# Generated by Django 5.1.6 on 2025-02-16 15:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_announcement_body_type_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyconditions',
            name='condition_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Moshina xolati'),
        ),
        migrations.AddField(
            model_name='bodyconditions',
            name='condition_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Moshina xolati'),
        ),
        migrations.AddField(
            model_name='bodyparts',
            name='body_name_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='moshina tanasi'),
        ),
        migrations.AddField(
            model_name='bodyparts',
            name='body_name_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='moshina tanasi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='brand',
            field=models.CharField(max_length=255, verbose_name='Mashina brandi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='brand_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Mashina brandi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='brand_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Mashina brandi'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='model',
            field=models.CharField(max_length=255, verbose_name='Moshina Model'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='model_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='Moshina Model'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='model_uz',
            field=models.CharField(max_length=255, null=True, verbose_name='Moshina Model'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='main.announcement', verbose_name='Elonlar'),
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.BigIntegerField(verbose_name='Narxi'),
        ),
    ]
