# Generated by Django 5.1.6 on 2025-02-17 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_bodyconditions_condition_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bodystatus',
            name='body_part',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodypart', to='main.bodyparts', verbose_name='Moshina tanasi'),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='car_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_status', to='main.announcement', verbose_name='Elon'),
        ),
        migrations.AlterField(
            model_name='bodystatus',
            name='condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition', to='main.bodyconditions', verbose_name='Moshina xolati'),
        ),
        migrations.AlterField(
            model_name='images',
            name='is_main',
            field=models.BooleanField(verbose_name='Asosiy rasm'),
        ),
    ]
