# Generated by Django 5.1.6 on 2025-02-19 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_announcement_slug_announcement_slug_from_lang'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='dealer',
            new_name='dealer_id',
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='user',
            new_name='user_id',
        ),
    ]
